### ISSUE TITLE
patch command in recipe needs `-p0` option

### ISSUE THREAD

**Issue by kinichiro** [Sp1l/LibreBSD-patches#2]
Hi,
About the 'recipe', I have a question.
Does `patch` command need `-p0` option, doesn't it ?

The command `patch < ~/download/patchset` changes /usr/src/Makefile too, and it broke build process.
The command `patch -p0 < ~/download/patchset` worked fine for me.

I'm using FreeBSD 10.3 (amd64).
I downloaded OS source code from ftp://ftp.freebsd.org/pub/FreeBSD/releases/amd64/10.3-RELEASE/src.txz
LibreSSL is http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.3.2.tar.gz
patch is https://github.com/Sp1l/LibreBSD/raw/FreeBSD-10.3/patchset/patchset

Best Regards,

**Comment by Sp1l** [comment]
Merged d07460155d8882855b53c2cc4ced7c2955bba3ab

Thanks for reporting
