### ISSUE TITLE
Buildworld fails at libdns and s3_both.c

### ISSUE THREAD

**Issue by mkohanim** [Sp1l/LibreBSD-patches#3]
Hi Bernard,

Unfortunately I do not have the logs. This said, however, I hope the following helps:
1. I used: https://github.com/freebsd/freebsd/tree/releng/11.0 (directly from the readme) as source
2. I followed all the instructions for patching the source
3. Issued 'make buildworld' in /usr/src
4. The first build failed in buffers.c (libdns) which included dane.h which included ssl.h with the following missing files (all of which were included with #include &lt;openssl/xx&gt;
e_os2.h
pqueue.h
symhack.h
5. I checked /usr/obj/usr/src/tmp/usr/include/openssl/ and those files were indeed missing so I copied those files from /usr/src/crypto/openssl/ and /usr/src/crypto/openssl/include to /usr/obj/usr/src/tmp/usr/include/openssl/
6. The build went farther this time but now it fails at:
cc -target x86_64-unknown-freebsd11.0 --sysroot=/usr/obj/usr/src/tmp -B/usr/obj/usr/src/tmp/usr/bin  -O2 -pipe   -fPIC -DPIC -I/usr/src/secure/lib/libssl/../../../crypto/openssl -DTERMIOS -DANSI_SOURCE -DOPENSSL_THREADS -DDSO_DLFCN -DHAVE_DLFCN_H -DL_ENDIAN -DOPENSSL_IA32_SSE2 -DAES_ASM -DBSAES_ASM -DVPAES_ASM -DECP_NISTZ256_ASM -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DMD5_ASM -DGHASH_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DWHIRLPOOL_ASM -I/usr/src/secure/lib/libssl/../../../crypto/openssl/crypto -MD  -MF.depend.s3_both.o -MTs3_both.o -std=gnu99 -fstack-protector-strong -Wno-pointer-sign -Wno-empty-body -Wno-string-plus-int -Wno-unused-const-variable -Wno-tautological-compare -Wno-unused-value -Wno-parentheses-equality -Wno-unused-function -Wno-enum-conversion -Wno-unused-local-typedef -Wno-switch -Wno-switch-enum -Wno-knr-promoted-parameter -Wno-parentheses  -Qunused-arguments  -c /usr/src/secure/lib/libssl/../../../crypto/openssl/ssl/s3_both.c -o s3_both.o
/usr/src/secure/lib/libssl/../../../crypto/openssl/ssl/s3_both.c:499:47: error: 
      use of undeclared identifier 'EVP_PKEY_DHX'
    } else if (x && (i == EVP_PKEY_DH || i == EVP_PKEY_DHX)) {
                                              ^
1 error generated.

Thank you.

**Comment by Sp1l** [comment]
Hi,

For some reason it's building the OpenSSL libs not the LibreSSL libs,..

> -I/usr/src/secure/lib/libssl/../../../crypto/openssl

Can you check the output of `make -VMK_LIBRESSL -VWITH_LIBRESSL` at minimum MK_LIBRESSL should respond with `yes`

**Comment by Sp1l** [comment]
Assuming that you hadn't added 

> WITH_LIBRESSL= "yes"

to your `/etc/src.conf` this was the issue. Please let me know if this fixes your problem!

**Comment by mkohanim** [comment]
Hi Bernard,

Thank YOU. I am building from scratch now. For your information, file /etc/src.conf didn't exist on my system and I didn't think I would need to do anything with it simply because of the instructions here:
https://github.com/Sp1l/LibreBSD and specifically:
(Add WITH_LIBRESSL=yes to /etc/src.conf) No longer required as it now is enabled by default

I shall keep you posted.

Thanks again and with kind regards,
Michel

**Comment by mkohanim** [comment]
Hi Bernard,

Unfortunately it didn't work:
===> lib/libldns (obj,all,install)
echo libprivateldns.so.5.full: /usr/obj/usr/src/tmp/usr/lib/libcrypto.a >> .depend
cc   -O2 -pipe -I/usr/src/lib/libldns/../../contrib/ldns   -MD  -MF.depend.buffer.o -MTbuffer.o -std=gnu99 -fstack-protector-strong -Wsystem-headers -Werror -Wall -Wno-format-y2k -W -Wno-unused-parameter -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wno-uninitialized -Wno-pointer-sign -Wno-empty-body -Wno-string-plus-int -Wno-unused-const-variable -Wno-tautological-compare -Wno-unused-value -Wno-parentheses-equality -Wno-unused-function -Wno-enum-conversion -Wno-unused-local-typedef  -Qunused-arguments  -c /usr/src/lib/libldns/../../contrib/ldns/buffer.c -o buffer.o
In file included from /usr/src/lib/libldns/../../contrib/ldns/buffer.c:12:
In file included from /usr/src/lib/libldns/../../contrib/ldns/ldns/ldns.h:98:
In file included from /usr/src/lib/libldns/../../contrib/ldns/ldns/dane.h:31:
/usr/obj/usr/src/tmp/usr/include/openssl/ssl.h:146:11: fatal error: 
      'openssl/e_os2.h' file not found

# include <openssl/e_os2.h>

```
      ^
```

1 error generated.
**\* Error code 1

Stop.
make[4]: stopped in /usr/src/lib/libldns
**\* Error code 1

Stop.
make[3]: stopped in /usr/src
**\* Error code 1

Stop.
make[2]: stopped in /usr/src
**\* Error code 1

Stop.
make[1]: stopped in /usr/src
**\* Error code 1

Stop.
make: stopped in /usr/src

**Comment by mkohanim** [comment]
Hi Bernard,

This is not solved for me. i have both WITH_LIBRESSL=yes (in /etc/src.conf) as well as MK_LIBRESSL (in /etc/make.conf). Still fails at the same spot.

Thank you.

With kind regards,
Michel
